name: ping_notification
description: "Ping Notification es una librería de Flutter"
version: 0.0.2
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  network_ping: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
